const agcenterInner = {
    name: '',
    i18n: 'AGENT_CENTER',
    hasLogo: false,
    hasLogin: true,
    hasLogout: true,
    hasBack: true,
    hasTitle: false,
    hasI18n: true,
    hasRouter: true,
    titleAlign: 'center',
    back: 'back',
    backTo: ''
};

const config = {
    home: {
        name: '', // 名稱
        i18n: 'S_HOME', // 字典檔
        hasLogo: true, // Logo
        hasLoginForm: true, // 登入欄位
        hasLoginInfo: true, // 登入資訊
        hasLogout: false, // 登出
        hasBack: false, // 上一頁
        hasTitle: false, // 標題
        hasI18n: false, // 字典檔
        hasRouter: true, // Router
        titleAlign: 'center', // 標題對齊位置
        back: null, // 上一頁Function
        backTo: '' // Page
    },
    joinMember: {
        name: '',
        i18n: 'S_JOIN_MEMBER',
        hasLogo: false,
        hasLoginForm: false,
        hasLoginInfo: false,
        hasLogout: false,
        hasBack: true,
        hasTitle: false,
        hasI18n: true,
        hasRouter: true,
        titleAlign: 'center',
        back: 'back',
        backTo: ''
    },
    joinAgent: {
        name: '',
        i18n: 'S_AGENT_JOIN',
        hasLogo: false,
        hasLoginForm: false,
        hasLoginInfo: false,
        hasLogout: false,
        hasBack: true,
        hasTitle: false,
        hasI18n: true,
        hasRouter: true,
        titleAlign: 'center',
        back: 'back',
        backTo: ''
    },
    login: {
        name: '',
        i18n: 'S_MEMBER_LOGIN',
        hasLogo: false,
        hasLoginForm: false,
        hasLoginInfo: false,
        hasLogout: false,
        hasBack: true,
        hasTitle: false,
        hasI18n: true,
        hasRouter: true,
        titleAlign: 'center',
        back: 'back',
        backTo: ''
    },
    agLogin: {
        name: '',
        i18n: 'S_AGENT_LOGIN',
        hasLogo: false,
        hasLoginForm: false,
        hasLoginInfo: false,
        hasLogout: false,
        hasBack: true,
        hasTitle: false,
        hasI18n: true,
        hasRouter: true,
        titleAlign: 'center',
        back: 'back',
        backTo: ''
    },
    forgetPwd: {
        name: '',
        i18n: 'S_PASSWORD_FORGET',
        hasLogo: false,
        hasLoginForm: false,
        hasLoginInfo: false,
        hasLogout: false,
        hasBack: true,
        hasTitle: false,
        hasI18n: true,
        hasRouter: true,
        titleAlign: 'center',
        back: 'back',
        backTo: ''
    },
    resetPwd: {
        name: '',
        i18n: 'S_PASSWORD_RESET',
        hasLogo: false,
        hasLoginForm: false,
        hasLoginInfo: false,
        hasLogout: false,
        hasBack: true,
        hasTitle: false,
        hasI18n: true,
        hasRouter: true,
        titleAlign: 'center',
        back: 'back',
        backTo: ''
    },
    casino: {
        name: '',
        i18n: 'S_CASINO',
        hasLogo: false,
        hasLoginForm: true,
        hasLoginInfo: true,
        hasLogout: false,
        hasBack: true,
        hasTitle: false,
        hasI18n: true,
        hasRouter: true,
        titleAlign: 'left',
        back: 'back',
        backTo: ''
    },
    card: {
        name: '',
        i18n: 'S_CARD',
        hasLogo: false,
        hasLoginForm: true,
        hasLoginInfo: true,
        hasLogout: false,
        hasBack: true,
        hasTitle: false,
        hasI18n: true,
        hasRouter: true,
        titleAlign: 'left',
        back: 'back',
        backTo: ''
    },
    mahjong: {
        name: '',
        i18n: 'S_MAHJONG_GAMIMG',
        hasLogo: false,
        hasLoginForm: true,
        hasLoginInfo: true,
        hasLogout: false,
        hasBack: true,
        hasTitle: false,
        hasI18n: true,
        hasRouter: true,
        titleAlign: 'left',
        back: 'back',
        backTo: ''
    },
    promotion: {
        name: '',
        i18n: 'S_PROMOTIONS',
        hasLogo: false,
        hasLoginForm: false,
        hasLoginInfo: false,
        hasLogout: false,
        hasBack: true,
        hasTitle: false,
        hasI18n: true,
        hasRouter: true,
        titleAlign: 'center',
        back: 'back',
        backTo: ''
    },
    changeLang: {
        name: '',
        i18n: 'S_CHANGE_LANG',
        hasLogo: false,
        hasLoginForm: false,
        hasLoginInfo: false,
        hasLogout: false,
        hasBack: true,
        hasTitle: false,
        hasI18n: true,
        hasRouter: true,
        titleAlign: 'center',
        back: 'back',
        backTo: ''
    },
    domain: {
        name: '',
        i18n: 'S_BACKUP_DOMAIN',
        hasLogo: false,
        hasLoginForm: false,
        hasLoginInfo: false,
        hasLogout: false,
        hasBack: false,
        hasTitle: false,
        hasI18n: false,
        hasRouter: false,
        titleAlign: 'center',
        back: 'back',
        backTo: ''
    },
    'agcenter-home': {
        name: '',
        i18n: 'AGENT_CENTER',
        hasLogo: false,
        hasLoginForm: false,
        hasLoginInfo: false,
        hasLogout: true,
        hasBack: false,
        hasTitle: false,
        hasI18n: true,
        hasRouter: true,
        titleAlign: 'center',
        back: null,
        backTo: ''
    },
    'agcenter-accountData': agcenterInner,
    'agcenter-bankCard': agcenterInner,
    'agcenter-financeReward': agcenterInner,
    'agcenter-financeWithdraw': agcenterInner,
    'agcenter-gameRecord': agcenterInner,
    'agcenter-message': agcenterInner,
    'agcenter-post': agcenterInner,
    'agcenter-reportMember': agcenterInner,
    'mcenter-home': {
        name: '',
        i18n: 'S_MEM_CENTER',
        hasLogo: false,
        hasLoginForm: false,
        hasLoginInfo: false,
        hasLogout: true,
        hasBack: true,
        hasTitle: false,
        hasI18n: true,
        hasRouter: true,
        titleAlign: 'center',
        back: 'push',
        backTo: '/mobile'
    },
    'mcenter-accountData': {
        name: '',
        i18n: 'S_MEM_CENTER',
        hasLogo: false,
        hasLoginForm: false,
        hasLoginInfo: false,
        hasLogout: true,
        hasBack: true,
        hasTitle: false,
        hasI18n: true,
        hasRouter: true,
        titleAlign: 'center',
        back: 'push',
        backTo: '/mobile/mcenter'
    },
    'mcenter-balanceTrans': {
        name: '',
        i18n: 'S_MEM_CENTER',
        hasLogo: false,
        hasLoginForm: false,
        hasLoginInfo: false,
        hasLogout: true,
        hasBack: true,
        hasTitle: false,
        hasI18n: true,
        hasRouter: true,
        titleAlign: 'center',
        back: 'push',
        backTo: '/mobile/mcenter'
    },
    'mcenter-bankCard': {
        name: '',
        i18n: 'S_MEM_CENTER',
        hasLogo: false,
        hasLoginForm: false,
        hasLoginInfo: false,
        hasLogout: true,
        hasBack: true,
        hasTitle: false,
        hasI18n: true,
        hasRouter: true,
        titleAlign: 'center',
        back: 'push',
        backTo: '/mobile/mcenter'
    },
    'mcenter-bankRebate': {
        name: '',
        i18n: 'S_MEM_CENTER',
        hasLogo: false,
        hasLoginForm: false,
        hasLoginInfo: false,
        hasLogout: true,
        hasBack: true,
        hasTitle: false,
        hasI18n: true,
        hasRouter: true,
        titleAlign: 'center',
        back: 'push',
        backTo: '/mobile/mcenter'
    },
    'mcenter-betRecord': {
        name: '',
        i18n: 'S_MEM_CENTER',
        hasLogo: false,
        hasLoginForm: false,
        hasLoginInfo: false,
        hasLogout: true,
        hasBack: true,
        hasTitle: false,
        hasI18n: true,
        hasRouter: true,
        titleAlign: 'center',
        back: 'push',
        backTo: '/mobile/mcenter'
    },
    'mcenter-bonusAccount': {
        name: '',
        i18n: 'S_MEM_CENTER',
        hasLogo: false,
        hasLoginForm: false,
        hasLoginInfo: false,
        hasLogout: true,
        hasBack: true,
        hasTitle: false,
        hasI18n: true,
        hasRouter: true,
        titleAlign: 'center',
        back: 'push',
        backTo: '/mobile/mcenter'
    },
    'mcenter-deposit': {
        name: '',
        i18n: 'S_MEM_CENTER',
        hasLogo: false,
        hasLoginForm: false,
        hasLoginInfo: false,
        hasLogout: true,
        hasBack: true,
        hasTitle: false,
        hasI18n: true,
        hasRouter: true,
        titleAlign: 'center',
        back: 'push',
        backTo: '/mobile/mcenter'
    },
    'mcenter-message': {
        name: '',
        i18n: 'S_MEM_CENTER',
        hasLogo: false,
        hasLoginForm: false,
        hasLoginInfo: false,
        hasLogout: true,
        hasBack: true,
        hasTitle: false,
        hasI18n: true,
        hasRouter: true,
        titleAlign: 'center',
        back: 'push',
        backTo: '/mobile/mcenter'
    },
    'mcenter-moneyDetail': {
        name: '',
        i18n: 'S_MEM_CENTER',
        hasLogo: false,
        hasLoginForm: false,
        hasLoginInfo: false,
        hasLogout: true,
        hasBack: true,
        hasTitle: false,
        hasI18n: true,
        hasRouter: true,
        titleAlign: 'center',
        back: 'push',
        backTo: '/mobile/mcenter'
    },
    'mcenter-post': {
        name: '',
        i18n: 'S_MEM_CENTER',
        hasLogo: false,
        hasLoginForm: false,
        hasLoginInfo: false,
        hasLogout: true,
        hasBack: true,
        hasTitle: false,
        hasI18n: true,
        hasRouter: true,
        titleAlign: 'center',
        back: 'push',
        backTo: '/mobile/mcenter'
    },
    'mcenter-withdraw': {
        name: '',
        i18n: 'S_MEM_CENTER',
        hasLogo: false,
        hasLoginForm: false,
        hasLoginInfo: false,
        hasLogout: true,
        hasBack: true,
        hasTitle: false,
        hasI18n: true,
        hasRouter: true,
        titleAlign: 'center',
        back: 'push',
        backTo: '/mobile/mcenter'
    },
    'mcenter-tcenter-commission': {
        name: '',
        i18n: 'S_TEAM_CENTER',
        hasLogo: false,
        hasLoginForm: false,
        hasLoginInfo: false,
        hasLogout: false,
        hasBack: true,
        hasTitle: false,
        hasI18n: true,
        hasRouter: true,
        titleAlign: 'center',
        back: 'push',
        backTo: '/mobile/mcenter'
    },
    'mcenter-tcenter-management': {
        name: '',
        i18n: 'S_TEAM_CENTER',
        hasLogo: false,
        hasLoginForm: false,
        hasLoginInfo: false,
        hasLogout: false,
        hasBack: true,
        hasTitle: false,
        hasI18n: true,
        hasRouter: true,
        titleAlign: 'center',
        back: 'push',
        backTo: '/mobile/mcenter'
    },
    'mcenter-tcenter-gameRecord': {
        name: '',
        i18n: 'S_TEAM_CENTER',
        hasLogo: false,
        hasLoginForm: false,
        hasLoginInfo: false,
        hasLogout: false,
        hasBack: true,
        hasTitle: false,
        hasI18n: true,
        hasRouter: true,
        titleAlign: 'center',
        back: 'push',
        backTo: '/mobile/mcenter'
    }
};

export default config;
