---
kind: pipeline
name: AllPipeline(QA)

platform:
  os: linux
  arch: amd64

steps:
- name: push2GCR-yabo
  image: plugins/gcr
  settings:
    build_args:
    - website=porn1
    json_key:
      from_secret: GOOGLE_CREDENTIALS
    repo: gcr.io/rd7-project/yaboxxx-web
    tags:
    - latest
    - ${DRONE_COMMIT}
    - ${DRONE_TAG}
  depends_on:
  - clone

- name: yaboGKE-qa(istio)
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-test
    project: rd7-project
    template: configs/yabo/.istio-kube.yml
    vars:
      deployName: yabo-frontend-proxy-qa
      env: qa
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: yabo-frontend-proxy-nginx-config-qa
      k8sNginxSSL: ""
      nfs: 10.27.1.218
      nodePool: env
      nodePoolName: qa
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-yabo

- name: push2GCR-sigua
  image: plugins/gcr
  settings:
    build_args:
    - website=sg1
    json_key:
      from_secret: GOOGLE_CREDENTIALS
    repo: gcr.io/rd7-project/yaboxxx-web
    tags:
    - latest
    - ${DRONE_COMMIT}
    - ${DRONE_TAG}
  depends_on:
  - clone

- name: siguaGKE-qa(istio)
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-test
    project: rd7-project
    template: configs/sigua/.istio-kube.yml
    vars:
      deployName: sigua-frontend-proxy-qa
      env: qa
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: sigua-frontend-proxy-nginx-config-qa
      k8sNginxSSL: ""
      nfs: 10.27.1.218
      nodePool: env
      nodePoolName: qa
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-sigua

- name: push2GCR-aubo
  image: plugins/gcr
  settings:
    build_args:
    - website=aobo1
    json_key:
      from_secret: GOOGLE_CREDENTIALS
    repo: gcr.io/rd7-project/yaboxxx-web
    tags:
    - latest
    - ${DRONE_COMMIT}
    - ${DRONE_TAG}
  depends_on:
  - clone

- name: auboGKE-qa(istio)
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-test
    project: rd7-project
    template: configs/aubo/.istio-kube.yml
    vars:
      deployName: aubo-frontend-qa
      env: qa
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: aubo-frontend-nginx-config-qa
      k8sNginxSSL: ""
      nfs: 10.27.1.218
      nodePool: env
      nodePoolName: qa
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-aubo

- name: push2GCR-sp51
  image: plugins/gcr
  settings:
    build_args:
    - website=sp1
    json_key:
      from_secret: GOOGLE_CREDENTIALS
    repo: gcr.io/rd7-project/yaboxxx-web
    tags:
    - latest
    - ${DRONE_COMMIT}
    - ${DRONE_TAG}
  depends_on:
  - clone

- name: sp51GKE-qa(istio)
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-test
    project: rd7-project
    template: configs/sp51/.istio-kube.yml
    vars:
      deployName: sp51-frontend-qa
      env: qa
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: sp51-frontend-nginx-config-qa
      k8sNginxSSL: ""
      nfs: 10.27.1.218
      nodePool: env
      nodePoolName: qa
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-sp51

trigger:
  event:
  - tag
  ref:
  - refs/tags/allQA-*

---
kind: pipeline
name: AllPipeline(Beta)

platform:
  os: linux
  arch: amd64

steps:
- name: push2GCR-yabo
  image: plugins/gcr
  settings:
    build_args:
    - website=porn1
    json_key:
      from_secret: GOOGLE_CREDENTIALS
    repo: gcr.io/rd7-project/yaboxxx-web
    tags:
    - latest
    - ${DRONE_COMMIT}
    - ${DRONE_TAG}
  depends_on:
  - clone

- name: yaboGKE-beta(istio)
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/yabo/.istio-kube.yml
    vars:
      deployName: yabo-frontend-proxy-beta
      env: beta
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: yabo-frontend-proxy-nginx-config-beta
      k8sNginxSSL: ""
      nfs: 10.17.3.48
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-yabo

- name: push2GCR-sigua
  image: plugins/gcr
  settings:
    build_args:
    - website=porn1
    json_key:
      from_secret: GOOGLE_CREDENTIALS
    repo: gcr.io/rd7-project/yaboxxx-web
    tags:
    - latest
    - ${DRONE_COMMIT}
    - ${DRONE_TAG}
  depends_on:
  - clone

- name: siguaGKE-beta(istio)
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/sigua/.istio-kube.yml
    vars:
      deployName: sigua-frontend-proxy-beta
      env: beta
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: sigua-frontend-proxy-nginx-config-beta
      k8sNginxSSL: ""
      nfs: 10.17.3.48
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-sigua

trigger:
  event:
  - tag
  ref:
  - refs/tags/allBeta-*

---
kind: pipeline
name: sp51-frontend-qaPipeline(istioQA)

platform:
  os: linux
  arch: amd64

steps:
- name: push2GCR-QA
  image: plugins/gcr
  settings:
    build_args:
    - website=sp1
    - product=sp51
    json_key:
      from_secret: GOOGLE_CREDENTIALS
    repo: gcr.io/rd7-project/yaboxxx-web
    tags:
    - latest
    - qa-${DRONE_COMMIT}
    - ${DRONE_TAG}

- name: deploy2GKE-QA
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-test
    project: rd7-project
    template: configs/sp51/.istio-kube.yml
    vars:
      deployName: sp51-frontend-qa
      env: qa
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: sp51-frontend-nginx-config-qa
      k8sNginxSSL: ""
      nfs: 10.27.1.218
      nodePool: env
      nodePoolName: qa
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS

trigger:
  event:
  - tag
  ref:
  - refs/tags/sp1QA-*

---
kind: pipeline
name: aubo-frontend-qaPipeline(istioQA)

platform:
  os: linux
  arch: amd64

steps:
- name: push2GCR-QA
  image: plugins/gcr
  settings:
    build_args:
    - website=aobo1
    - product=aubo
    json_key:
      from_secret: GOOGLE_CREDENTIALS
    repo: gcr.io/rd7-project/yaboxxx-web
    tags:
    - latest
    - qa-${DRONE_COMMIT}
    - ${DRONE_TAG}

- name: deploy2GKE-QA
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-test
    project: rd7-project
    template: configs/aubo/.istio-kube.yml
    vars:
      deployName: aubo-frontend-qa
      env: qa
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: aubo-frontend-nginx-config-qa
      k8sNginxSSL: ""
      nfs: 10.27.1.218
      nodePool: env
      nodePoolName: qa
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS

trigger:
  event:
  - tag
  ref:
  - refs/tags/aobo1QA-*

---
kind: pipeline
name: sigua-frontend-proxy-qaPipeline(istioQA)

platform:
  os: linux
  arch: amd64

steps:
- name: push2GCR-QA
  image: plugins/gcr
  settings:
    build_args:
    - website=sg1
    - product=sigua
    json_key:
      from_secret: GOOGLE_CREDENTIALS
    repo: gcr.io/rd7-project/yaboxxx-web
    tags:
    - latest
    - qa-${DRONE_COMMIT}
    - ${DRONE_TAG}

- name: deploy2GKE-QA
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-test
    project: rd7-project
    template: configs/sigua/.istio-kube.yml
    vars:
      deployName: sigua-frontend-proxy-qa
      env: qa
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: sigua-frontend-proxy-nginx-config-qa
      k8sNginxSSL: ""
      nfs: 10.27.1.218
      nodePool: env
      nodePoolName: qa
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS

trigger:
  event:
  - tag
  ref:
  - refs/tags/sg1QA-*

---
kind: pipeline
name: sigua-frontend-proxy-betaPipeline(istioBeta)

platform:
  os: linux
  arch: amd64

steps:
- name: push2GCR-Beta
  image: plugins/gcr
  settings:
    build_args:
    - website=sg1
    - product=sigua
    json_key:
      from_secret: GOOGLE_CREDENTIALS
    repo: gcr.io/rd7-project/yaboxxx-web
    tags:
    - latest
    - beta-${DRONE_COMMIT}
    - ${DRONE_TAG}

- name: deploy2GKE-Beta
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/sigua/.istio-kube.yml
    vars:
      deployName: sigua-frontend-proxy-beta
      env: beta
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: sigua-frontend-proxy-nginx-config-beta
      k8sNginxSSL: ""
      nfs: 10.17.3.48
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS

trigger:
  event:
  - tag
  ref:
  - refs/tags/sg1Beta-*

---
kind: pipeline
name: sigua-frontend-proxy-qa2Pipeline(istioQA)

platform:
  os: linux
  arch: amd64

steps:
- name: push2GCR-QA
  image: plugins/gcr
  settings:
    build_args:
    - website=sg2
    - product=sigua
    json_key:
      from_secret: GOOGLE_CREDENTIALS
    repo: gcr.io/rd7-project/yaboxxx-web
    tags:
    - latest
    - qa2-${DRONE_COMMIT}
    - ${DRONE_TAG}

- name: deploy2GKE-QA
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-test
    project: rd7-project
    template: configs/sigua/.istio-kube.yml
    vars:
      deployName: sigua-frontend-proxy-qa2
      env: qa2
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: sigua-frontend-proxy-nginx-config-qa2
      k8sNginxSSL: ""
      nfs: 10.27.1.218
      nodePool: env
      nodePoolName: qa
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS

trigger:
  event:
  - tag
  ref:
  - refs/tags/sg2QA-*

---
kind: pipeline
name: yabo-frontend-proxy-qaPipeline(istioQA)

platform:
  os: linux
  arch: amd64

steps:
- name: push2GCR-QA
  image: plugins/gcr
  settings:
    build_args:
    - website=porn1
    - product=yabo
    json_key:
      from_secret: GOOGLE_CREDENTIALS
    repo: gcr.io/rd7-project/yaboxxx-web
    tags:
    - latest
    - qa-${DRONE_COMMIT}
    - ${DRONE_TAG}

- name: deploy2GKE-QA
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-test
    project: rd7-project
    template: configs/yabo/.istio-kube.yml
    vars:
      deployName: yabo-frontend-proxy-qa
      env: qa
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: yabo-frontend-proxy-nginx-config-qa
      k8sNginxSSL: ""
      nfs: 10.27.1.218
      nodePool: env
      nodePoolName: qa
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS

trigger:
  event:
  - tag
  ref:
  - refs/tags/porn1QA-*

---
kind: pipeline
name: yabo-frontend-proxy-betaPipeline(istioBeta)

platform:
  os: linux
  arch: amd64

steps:
- name: push2GCR-Beta
  image: plugins/gcr
  settings:
    build_args:
    - website=porn1
    - product=yabo
    json_key:
      from_secret: GOOGLE_CREDENTIALS
    repo: gcr.io/rd7-project/yaboxxx-web
    tags:
    - latest
    - beta-${DRONE_COMMIT}
    - ${DRONE_TAG}

- name: deploy2GKE-Beta
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/yabo/.istio-kube.yml
    vars:
      deployName: yabo-frontend-proxy-beta
      env: beta
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: yabo-frontend-proxy-nginx-config-beta
      k8sNginxSSL: ""
      nfs: 10.17.3.48
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS

trigger:
  event:
  - tag
  ref:
  - refs/tags/porn1Beta-*

...
