---
kind: pipeline
name: AllPipeline(Prod)

platform:
  os: linux
  arch: amd64

steps:
- name: push2GCR-Prod
  image: plugins/gcr
  settings:
    json_key:
      from_secret: GOOGLE_CREDENTIALS
    repo: gcr.io/rd7-project/yaboxxx-web
    tags:
    - latest
    - ${DRONE_COMMIT}
    - ${DRONE_TAG}
  depends_on:
  - clone

- name: yaboGKE-demo(istio)
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/yabo/.istio-kube.yml
    vars:
      deployName: yabo-frontend-proxy-demo
      env: demo
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: yabo-frontend-proxy-nginx-config-demo
      k8sNginxSSL: ""
      nfs: 10.17.1.94
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-Prod

- name: yaboGKE-prod(istio)
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/yabo/.istio-kube.yml
    vars:
      deployName: yabo-frontend-proxy-prod
      env: prod
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: yabo-frontend-proxy-nginx-config-prod
      k8sNginxSSL: ""
      nfs: 10.17.1.94
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-Prod

- name: siguaGKE-demo(istio)
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/sigua/.istio-kube.yml
    vars:
      deployName: sigua-frontend-proxy-demo
      env: demo
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: sigua-frontend-proxy-nginx-config-demo
      k8sNginxSSL: ""
      nfs: 10.17.1.94
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-Prod

- name: siguaGKE-prod(istio)
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/sigua/.istio-kube.yml
    vars:
      deployName: sigua-frontend-proxy-prod
      env: prod
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: sigua-frontend-proxy-nginx-config-prod
      k8sNginxSSL: ""
      nfs: 10.17.1.94
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-Prod

- name: auboGKE-demo(istio)
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/aubo/.istio-kube.yml
    vars:
      deployName: aubo-frontend-demo
      env: demo
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: aubo-frontend-nginx-config-demo
      k8sNginxSSL: ""
      nfs: 10.17.1.94
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-Prod

- name: auboGKE-prod(istio)
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/aubo/.istio-kube.yml
    vars:
      deployName: aubo-frontend-prod
      env: prod
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: aubo-frontend-nginx-config-prod
      k8sNginxSSL: ""
      nfs: 10.17.1.94
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-Prod

- name: sp51GKE-demo(istio)
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/sp51/.istio-kube.yml
    vars:
      deployName: sp51-frontend-demo
      env: demo
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: sp51-frontend-nginx-config-demo
      k8sNginxSSL: ""
      nfs: 10.17.1.94
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-Prod

- name: sp51GKE-prod(istio)
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/sp51/.istio-kube.yml
    vars:
      deployName: sp51-frontend-prod
      env: prod
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: sp51-frontend-nginx-config-prod
      k8sNginxSSL: ""
      nfs: 10.17.1.94
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-Prod

trigger:
  event:
  - tag
  ref:
  - refs/tags/allProd-*

---
kind: pipeline
name: sp51-frontend-demoPipeline(istioDemo)

platform:
  os: linux
  arch: amd64

steps:
- name: push2GCR-Demo
  image: plugins/gcr
  settings:
    build_args:
    - website=demo
    - product=sp51
    json_key:
      from_secret: GOOGLE_CREDENTIALS
    repo: gcr.io/rd7-project/yaboxxx-web
    tags:
    - latest
    - demo-${DRONE_COMMIT}
    - ${DRONE_TAG}
  depends_on:
  - clone

- name: deploy2GKE-Demo
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/sp51/.istio-kube.yml
    vars:
      deployName: sp51-frontend-demo
      env: demo
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: sp51-frontend-nginx-config-demo
      k8sNginxSSL: ""
      nfs: 10.17.1.94
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-Demo

trigger:
  event:
  - tag
  ref:
  - refs/tags/spDemo-*

---
kind: pipeline
name: Buildsp51Pipeline(istioProd)

platform:
  os: linux
  arch: amd64

steps:
- name: push2GCR-Prod
  image: plugins/gcr
  settings:
    build_args:
    - website=demo
    - product=sp51
    json_key:
      from_secret: GOOGLE_CREDENTIALS
    repo: gcr.io/rd7-project/yaboxxx-web
    tags:
    - latest
    - demo-${DRONE_COMMIT}
    - ${DRONE_TAG}
  depends_on:
  - clone

- name: deploy2GKE-demo
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/sp51/.istio-kube.yml
    vars:
      deployName: sp51-frontend-demo
      env: demo
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: sp51-frontend-nginx-config-demo
      k8sNginxSSL: ""
      nfs: 10.17.1.94
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-Prod

- name: deploy2GKE-prod
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/sp51/.istio-kube.yml
    vars:
      deployName: sp51-frontend-prod
      env: prod
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: sp51-frontend-nginx-config-prod
      k8sNginxSSL: ""
      nfs: 10.17.1.94
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-Prod

trigger:
  event:
  - tag
  ref:
  - refs/tags/spProd-*

---
kind: pipeline
name: aubo-frontend-demoPipeline(istioDemo)

platform:
  os: linux
  arch: amd64

steps:
- name: push2GCR-Demo
  image: plugins/gcr
  settings:
    build_args:
    - website=demo
    - product=aubo
    json_key:
      from_secret: GOOGLE_CREDENTIALS
    repo: gcr.io/rd7-project/yaboxxx-web
    tags:
    - latest
    - demo-${DRONE_COMMIT}
    - ${DRONE_TAG}
  depends_on:
  - clone

- name: deploy2GKE-Demo
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/aubo/.istio-kube.yml
    vars:
      deployName: aubo-frontend-demo
      env: demo
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: aubo-frontend-nginx-config-demo
      k8sNginxSSL: ""
      nfs: 10.17.1.94
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-Demo

trigger:
  event:
  - tag
  ref:
  - refs/tags/abDemo-*

---
kind: pipeline
name: BuildauboPipeline(istioProd)

platform:
  os: linux
  arch: amd64

steps:
- name: push2GCR-Prod
  image: plugins/gcr
  settings:
    build_args:
    - website=demo
    - product=aubo
    json_key:
      from_secret: GOOGLE_CREDENTIALS
    repo: gcr.io/rd7-project/yaboxxx-web
    tags:
    - latest
    - demo-${DRONE_COMMIT}
    - ${DRONE_TAG}
  depends_on:
  - clone

- name: deploy2GKE-demo
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/aubo/.istio-kube.yml
    vars:
      deployName: aubo-frontend-demo
      env: demo
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: aubo-frontend-nginx-config-demo
      k8sNginxSSL: ""
      nfs: 10.17.1.94
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-Prod

- name: deploy2GKE-prod
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/aubo/.istio-kube.yml
    vars:
      deployName: aubo-frontend-prod
      env: prod
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: aubo-frontend-nginx-config-prod
      k8sNginxSSL: ""
      nfs: 10.17.1.94
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-Prod

trigger:
  event:
  - tag
  ref:
  - refs/tags/abProd-*

---
kind: pipeline
name: sigua-frontend-proxy-demoPipeline(istioDemo)

platform:
  os: linux
  arch: amd64

steps:
- name: push2GCR-Demo
  image: plugins/gcr
  settings:
    build_args:
    - website=demo
    - product=sigua
    json_key:
      from_secret: GOOGLE_CREDENTIALS
    repo: gcr.io/rd7-project/yaboxxx-web
    tags:
    - latest
    - demo-${DRONE_COMMIT}
    - ${DRONE_TAG}
  depends_on:
  - clone

- name: deploy2GKE-Demo
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/sigua/.istio-kube.yml
    vars:
      deployName: sigua-frontend-proxy-demo
      env: demo
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: sigua-frontend-proxy-nginx-config-demo
      k8sNginxSSL: ""
      nfs: 10.17.1.94
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-Demo

trigger:
  event:
  - tag
  ref:
  - refs/tags/sgDemo-*

---
kind: pipeline
name: BuildsiguaPipeline(istioProd)

platform:
  os: linux
  arch: amd64

steps:
- name: push2GCR-Prod
  image: plugins/gcr
  settings:
    build_args:
    - website=demo
    - product=sigua
    json_key:
      from_secret: GOOGLE_CREDENTIALS
    repo: gcr.io/rd7-project/yaboxxx-web
    tags:
    - latest
    - demo-${DRONE_COMMIT}
    - ${DRONE_TAG}
  depends_on:
  - clone

- name: deploy2GKE-demo
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/sigua/.istio-kube.yml
    vars:
      deployName: sigua-frontend-proxy-demo
      env: demo
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: sigua-frontend-proxy-nginx-config-demo
      k8sNginxSSL: ""
      nfs: 10.17.1.94
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-Prod

- name: deploy2GKE-prod
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/sigua/.istio-kube.yml
    vars:
      deployName: sigua-frontend-proxy-prod
      env: prod
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: sigua-frontend-proxy-nginx-config-prod
      k8sNginxSSL: ""
      nfs: 10.17.1.94
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-Prod

trigger:
  event:
  - tag
  ref:
  - refs/tags/sgProd-*

---
kind: pipeline
name: yabo-frontend-proxy-demoPipeline(istioDemo)

platform:
  os: linux
  arch: amd64

steps:
- name: push2GCR-Demo
  image: plugins/gcr
  settings:
    build_args:
    - website=demo
    - product=yabo
    json_key:
      from_secret: GOOGLE_CREDENTIALS
    repo: gcr.io/rd7-project/yaboxxx-web
    tags:
    - latest
    - demo-${DRONE_COMMIT}
    - ${DRONE_TAG}
  depends_on:
  - clone

- name: deploy2GKE-Demo
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/yabo/.istio-kube.yml
    vars:
      deployName: yabo-frontend-proxy-demo
      env: demo
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: yabo-frontend-proxy-nginx-config-demo
      k8sNginxSSL: ""
      nfs: 10.17.1.94
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-Demo

trigger:
  event:
  - tag
  ref:
  - refs/tags/ybDemo-*

---
kind: pipeline
name: BuildyaboPipeline(istioProd)

platform:
  os: linux
  arch: amd64

steps:
- name: push2GCR-Prod
  image: plugins/gcr
  settings:
    build_args:
    - website=demo
    - product=yabo
    json_key:
      from_secret: GOOGLE_CREDENTIALS
    repo: gcr.io/rd7-project/yaboxxx-web
    tags:
    - latest
    - demo-${DRONE_COMMIT}
    - ${DRONE_TAG}
  depends_on:
  - clone

- name: deploy2GKE-demo
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/yabo/.istio-kube.yml
    vars:
      deployName: yabo-frontend-proxy-demo
      env: demo
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: yabo-frontend-proxy-nginx-config-demo
      k8sNginxSSL: ""
      nfs: 10.17.1.94
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-Prod

- name: deploy2GKE-prod
  image: nytimes/drone-gke
  settings:
    cluster: yaboxxx-prod
    project: rd7-project
    template: configs/yabo/.istio-kube.yml
    vars:
      deployName: yabo-frontend-proxy-prod
      env: prod
      imageName: gcr.io/rd7-project/yaboxxx-web:${DRONE_TAG}
      k8sNginxConfigMap: yabo-frontend-proxy-nginx-config-prod
      k8sNginxSSL: ""
      nfs: 10.17.1.94
      nodePool: env
      nodePoolName: prod
    zone: asia-east1-b
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDENTIALS
  depends_on:
  - push2GCR-Prod

trigger:
  event:
  - tag
  ref:
  - refs/tags/ybProd-*

...
