# _DEPLOY_TYPE
# _CLUSTER_PROJECT
# _CLUSTER_ZONE
# _CLUSTER_NAME
# _CLUSTER_DEPLOY
# _CLUSTER_CONTAINER
steps:
  - name: gcr.io/cloud-builders/yarn:node-8.12.0
    dir: ./resource
    id: A
  - name: gcr.io/cloud-builders/yarn:node-8.12.0
    dir: ./resource
    args:
      - run
      - build
      - $_CDN_HOST1
    waitFor:
      - A

  # - name: gcr.io/cloud-builders/yarn:node-8.12.0
  #   dir: ./resource
  #   args:
  #     - run
  #     - build
  #     - $_CDN_HOST2
  #   waitFor:
  #     - A

  # - name: gcr.io/cloud-builders/yarn:node-8.12.0
  #   dir: ./resource
  #   args:
  #     - run
  #     - build
  #     - $_CDN_HOST2
  #   waitFor:
  #     - A

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/$REPO_NAME-$_DEPLOY_TYPE:z-$REVISION_ID
      - -t
      - gcr.io/$PROJECT_ID/$REPO_NAME-$_DEPLOY_TYPE:latest
      - -f
      - Dockerfile
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/$REPO_NAME-$_DEPLOY_TYPE:z-$REVISION_ID

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/$REPO_NAME-$_DEPLOY_TYPE:latest

  - name: gcr.io/cloud-builders/gcloud
    args:
      - --project=$_CLUSTER_PROJECT
      - container
      - clusters
      - get-credentials
      - --zone=$_CLUSTER_ZONE
      - $_CLUSTER_NAME

  - name: gcr.io/cloud-builders/kubectl
    env:
      - CLOUDSDK_CORE_PROJECT=$_CLUSTER_PROJECT
      - CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME
      - CLOUDSDK_COMPUTE_ZONE=$_CLUSTER_ZONE
    args:
      - set
      - image
      - --namespace=$_NAME_SPACE
      - deploy/$_CLUSTER_DEPLOY
      - $_CLUSTER_CONTAINER=gcr.io/$PROJECT_ID/$REPO_NAME-$_DEPLOY_TYPE:z-$REVISION_ID

options:
  machineType: 'N1_HIGHCPU_8'

timeout: 1800s
