export default {
    normal: {
        homeEy1: () => import(/* webpackChunkName: 'homeEy1' */'../../tpl/ey1/components/home'),
        loginEy1: () => import(/* webpackChunkName: 'loginEy1' */'../../tpl/ey1/components/login'),
        // casinoEy1: () => import(/* webpackChunkName: 'casinoEy1' */'../../tpl/ey1/components/casino'),
        // cardEy1: () => import(/* webpackChunkName: 'cardEy1' */'../../tpl/ey1/components/card'),
        // mahjongEy1: () => import(/* webpackChunkName: 'mahjongEy1' */'../../tpl/ey1/components/mahjong'),
        // promotionEy1: () => import(/* webpackChunkName: 'promotionEy1' */'../../tpl/ey1/components/promotion'),
        // forgetPwdEy1: () => import(/* webpackChunkName: 'forgetPwdEy1' */'../../tpl/ey1/components/forgetPwd'),
        // resetPwdEy1: () => import(/* webpackChunkName: 'resetPwdEy1' */'../../tpl/ey1/components/resetPwd'),
        joinMemberEy1: () => import(/* webpackChunkName: 'joinMemberEy1' */'../../tpl/ey1/components/joinMember'),
        // fishareaEy1: () => import(/* webpackChunkName: 'fishareaEy1' */'../../tpl/ey1/components/fisharea'),
        serviceEy1: () => import(/* webpackChunkName: 'serviceEy1' */'../../tpl/ey1/components/service'),
        // webviewEy1: () => import(/* webpackChunkName: 'webviewEy1' */'../../tpl/ey1/components/webview'),
        // installEy1: () => import(/* webpackChunkName: 'installEy1' */'../../tpl/ey1/components/install'),
        // shareDownloadEy1: () => import(/* webpackChunkName: 'shareDownloadEy1' */ '../../tpl/ey1/components/shareDownload'),
        launchEy1: () => import(/* webpackChunkName: 'launchEy1' */ '../../tpl/ey1/components/launch')
    },
    mcenter: {
        homeEy1: () => import(/* webpackChunkName: 'homeEy1' */'../../tpl/ey1/components/mcenter/components/home'),
        // accountDataEy1: () => import(/* webpackChunkName: 'accountDataEy1' */'../../tpl/ey1/components/mcenter/components/accountData'),
        //     bindingDeviceEy1: () => import(/* webpackChunkName: 'bindingDeviceEy1' */'../../tpl/ey1/components/mcenter/components/bindingDevice'),
        //     balanceTransEy1: () => import(/* webpackChunkName: 'balanceTransEy1' */'../../tpl/ey1/components/mcenter/components/balanceTrans'),
        //     creditTransEy1: () => import(/* webpackChunkName: 'creditTransEy1' */'../../tpl/ey1/components/mcenter/components/creditTrans'),
        //     bankCardEy1: () => import(/* webpackChunkName: 'bankCardEy1' */'../../tpl/ey1/components/mcenter/components/bankCard'),
        //     bankRebateEy1: () => import(/* webpackChunkName: 'bankRebateEy1' */'../../tpl/ey1/components/mcenter/components/bankRebate'),
        //     betRecordEy1: () => import(/* webpackChunkName: 'betRecordEy1' */'../../tpl/ey1/components/mcenter/components/betRecord'),
        //     bonusAccountEy1: () => import(/* webpackChunkName: 'bonusAccountEy1' */'../../tpl/ey1/components/mcenter/components/bonusAccount'),
        //     moneyDetailEy1: () => import(/* webpackChunkName: 'moneyDetailEy1' */'../../tpl/ey1/components/mcenter/components/moneyDetail'),
        //     informationEy1: () => import(/* webpackChunkName: 'informationEy1' */'../../tpl/ey1/components/mcenter/components/information'),
        //     withdrawEy1: () => import(/* webpackChunkName: 'withdrawEy1' */'../../tpl/ey1/components/mcenter/components/withdraw'),
        //     depositEy1: () => import(/* webpackChunkName: 'depositEy1' */'../../tpl/ey1/components/mcenter/components/deposit'),
        //     accountVipEy1: () => import(/* webpackChunkName: 'accountVipEy1' */'../../tpl/ey1/components/mcenter/components/accountVip'),
        //     accountVipDetailEy1: () => import(/* webpackChunkName: 'accountVipDetailEy1' */'../../tpl/ey1/components/mcenter/components/accountVip/components/vipDetail'),
        //     tcenterCommissionEy1: () => import(/* webpackChunkName: 'tcenterCommissionEy1' */'../../tpl/ey1/components/mcenter/components/tcenter/components/commission'),
        //     tcenterGameRecordEy1: () => import(/* webpackChunkName: 'tcenterGameRecordEy1' */'../../tpl/ey1/components/mcenter/components/tcenter/components/gameRecord'),
        //     tcenterManagementEy1: () => import(/* webpackChunkName: 'tcenterManagementEy1' */'../../tpl/ey1/components/mcenter/components/tcenter/components/management'),
        //     tcenterRecommendGiftEy1: () => import(/* webpackChunkName: 'tcenteRecommendGiftEy1' */'../../tpl/ey1/components/mcenter/components/tcenter/components/recommendGift'),
        aboutEy1: () => import(/* webpackChunkName: 'aboutEy1' */'../../tpl/ey1/components/mcenter/components/about'),
        //     settingEy1: () => import(/* webpackChunkName: 'settingEy1' */'../../tpl/ey1/components/mcenter/components/setting'),
        //     feedbackEy1: () => import(/* webpackChunkName: 'feedbackEy1' */'../../tpl/ey1/components/mcenter/components/feedback'),
        //     helpEy1: () => import(/* webpackChunkName: 'helpEy1' */'../../tpl/ey1/components/mcenter/components/help'),
        //     helpDepositEy1: () => import(/* webpackChunkName: 'helpDepositEy1' */'../../tpl/ey1/components/mcenter/components/help/page/deposit'),
        //     helpWithdrawEy1: () => import(/* webpackChunkName: 'helpWithdrawEy1' */'../../tpl/ey1/components/mcenter/components/help/page/withdraw'),
        //     helpGameintroEy1: () => import(/* webpackChunkName: 'helpGameintroEy1' */'../../tpl/ey1/components/mcenter/components/help/page/gameintro'),
        //     helpSupportEy1: () => import(/* webpackChunkName: 'helpSupportEy1' */'../../tpl/ey1/components/mcenter/components/help/page/support'),
        //     helpContactEy1: () => import(/* webpackChunkName: 'helpContactEy1' */'../../tpl/ey1/components/mcenter/components/help/page/contact'),
        //     helpDetailEy1: () => import(/* webpackChunkName: 'helpDetailEy1' */'../../tpl/ey1/components/mcenter/components/help/page/detail'),
        //     accountDataNameEy1: () => import(/* webpackChunkName: 'accountDataNameEy1' */'../../tpl/ey1/components/mcenter/components/accountData/account/form/editName'),
        //     accountDataPhoneEy1: () => import(/* webpackChunkName: 'accountDataPhoneEy1' */'../../tpl/ey1/components/mcenter/components/accountData/account/form/editPhone'),
        //     accountDataEmailEy1: () => import(/* webpackChunkName: 'accountDataEmailEy1' */'../../tpl/ey1/components/mcenter/components/accountData/account/form/editEmail'),
        //     accountDataQqEy1: () => import(/* webpackChunkName: 'accountDataQqEy1' */'../../tpl/ey1/components/mcenter/components/accountData/account/form/editQq'),
        //     accountDataWeixinEy1: () => import(/* webpackChunkName: 'accountDataWeixinEy1' */'../../tpl/ey1/components/mcenter/components/accountData/account/form/editWeixin'),
        //     accountDataBirthdayEy1: () => import(/* webpackChunkName: 'accountDataBirthdayEy1' */'../../tpl/ey1/components/mcenter/components/accountData/account/form/editBirthday'),
        //     walletEy1: () => import(/* webpackChunkName: 'walletEy1' */'../../tpl/ey1/components/mcenter/components/wallet'),
        //     makeMoneyEy1: () => import(/* webpackChunkName: 'makeMoneyEy1' */'../../tpl/ey1/components/mcenter/components/makeMoney')
    }
};
