export default {
    normal: {
        homePorn1: () => import(/* webpackChunkName: 'homePorn1' */'../../tpl/porn1/components/home'),
        loginPorn1: () => import(/* webpackChunkName: 'loginPorn1' */'../../tpl/porn1/components/login'),
        casinoPorn1: () => import(/* webpackChunkName: 'casinoPorn1' */'../../tpl/porn1/components/casino'),
        cardPorn1: () => import(/* webpackChunkName: 'cardPorn1' */'../../tpl/porn1/components/card'),
        mahjongPorn1: () => import(/* webpackChunkName: 'mahjongPorn1' */'../../tpl/porn1/components/mahjong'),
        promotionPorn1: () => import(/* webpackChunkName: 'promotionPorn1' */'../../tpl/porn1/components/promotion'),
        forgetPwdPorn1: () => import(/* webpackChunkName: 'forgetPwdPorn1' */'../../tpl/porn1/components/forgetPwd'),
        resetPwdPorn1: () => import(/* webpackChunkName: 'resetPwdPorn1' */'../../tpl/porn1/components/resetPwd'),
        videoPlayPorn1: () => import(/* webpackChunkName: 'videoPlayPorn1' */'../../tpl/porn1/components/videoPlay'),
        videoListPorn1: () => import(/* webpackChunkName: 'videoListPorn1' */'../../tpl/porn1/components/videoList'),
        discoverPorn1: () => import(/* webpackChunkName: 'discoverPorn1' */'../../tpl/porn1/components/discover'),
        artistPorn1: () => import(/* webpackChunkName: 'artistPorn1' */'../../tpl/porn1/components/artist'),
        searchPorn1: () => import(/* webpackChunkName: 'searchPorn1' */'../../tpl/porn1/components/search'),
        tagPorn1: () => import(/* webpackChunkName: 'tagPorn1' */'../../tpl/porn1/components/tag'),
        joinMemberPorn1: () => import(/* webpackChunkName: 'joinMemberPorn1' */'../../tpl/porn1/components/joinMember'),
        liveStreamPorn1: () => import(/* webpackChunkName: 'liveStreamPorn1' */'../../tpl/porn1/components/liveStream'),
        fishareaPorn1: () => import(/* webpackChunkName: 'fishareaPorn1' */'../../tpl/porn1/components/fisharea')
    },
    mcenter: {
        homePorn1: () => import(/* webpackChunkName: 'homePorn1' */'../../tpl/porn1/components/mcenter/components/home'),
        accountDataPorn1: () => import(/* webpackChunkName: 'accountDataPorn1' */'../../tpl/porn1/components/mcenter/components/accountData'),
        bindingDevicePorn1: () => import(/* webpackChunkName: 'bindingDevicePorn1' */'../../tpl/porn1/components/mcenter/components/bindingDevice'),
        balanceTransPorn1: () => import(/* webpackChunkName: 'balanceTransPorn1' */'../../tpl/porn1/components/mcenter/components/balanceTrans'),
        bankCardPorn1: () => import(/* webpackChunkName: 'bankCardPorn1' */'../../tpl/porn1/components/mcenter/components/bankCard'),
        bankRebatePorn1: () => import(/* webpackChunkName: 'bankRebatePorn1' */'../../tpl/porn1/components/mcenter/components/bankRebate'),
        betRecordPorn1: () => import(/* webpackChunkName: 'betRecordPorn1' */'../../tpl/porn1/components/mcenter/components/betRecord'),
        bonusAccountPorn1: () => import(/* webpackChunkName: 'bonusAccountPorn1' */'../../tpl/porn1/components/mcenter/components/bonusAccount'),
        messagePorn1: () => import(/* webpackChunkName: 'messagePorn1' */'../../tpl/porn1/components/mcenter/components/message'),
        moneyDetailPorn1: () => import(/* webpackChunkName: 'moneyDetailPorn1' */'../../tpl/porn1/components/mcenter/components/moneyDetail'),
        informationPorn1: () => import(/* webpackChunkName: 'informationPorn1' */'../../tpl/porn1/components/mcenter/components/information'),
        postPorn1: () => import(/* webpackChunkName: 'postPorn1' */'../../tpl/porn1/components/mcenter/components/post'),
        withdrawPorn1: () => import(/* webpackChunkName: 'withdrawPorn1' */'../../tpl/porn1/components/mcenter/components/withdraw'),
        depositPorn1: () => import(/* webpackChunkName: 'depositPorn1' */'../../tpl/porn1/components/mcenter/components/deposit'),
        accountVipPorn1: () => import(/* webpackChunkName: 'accountVipPorn1' */'../../tpl/porn1/components/mcenter/components/accountVip'),
        tcenterCommissionPorn1: () => import(/* webpackChunkName: 'tcenterCommissionPorn1' */'../../tpl/porn1/components/mcenter/components/tcenter/components/commission'),
        tcenterGameRecordPorn1: () => import(/* webpackChunkName: 'tcenterGameRecordPorn1' */'../../tpl/porn1/components/mcenter/components/tcenter/components/gameRecord'),
        tcenterManagementPorn1: () => import(/* webpackChunkName: 'tcenterManagementPorn1' */'../../tpl/porn1/components/mcenter/components/tcenter/components/management')
    }
};
