export default {
    normal: {
        iframePorn1: () => import(/* webpackChunkName: 'iframePorn1' */'../../tpl/porn1/components/iframe'),
        homePorn1: () => import(/* webpackChunkName: 'homePorn1' */'../../tpl/porn1/components/home'),
        loginPorn1: () => import(/* webpackChunkName: 'loginPorn1' */'../../tpl/porn1/components/login'),
        casinoPorn1: () => import(/* webpackChunkName: 'casinoPorn1' */'../../tpl/porn1/components/casino'),
        cardPorn1: () => import(/* webpackChunkName: 'cardPorn1' */'../../tpl/porn1/components/card'),
        mahjongPorn1: () => import(/* webpackChunkName: 'mahjongPorn1' */'../../tpl/porn1/components/mahjong'),
        promotionPorn1: () => import(/* webpackChunkName: 'promotionPorn1' */'../../tpl/porn1/components/promotion'),
        forgetPwdPorn1: () => import(/* webpackChunkName: 'forgetPwdPorn1' */'../../tpl/porn1/components/forgetPwd'),
        resetPwdPorn1: () => import(/* webpackChunkName: 'resetPwdPorn1' */'../../tpl/porn1/components/resetPwd'),
        videoPlayPorn1: () => import(/* webpackChunkName: 'videoPlayPorn1' */'../../tpl/porn1/components/videoPlay'),
        videoListPorn1: () => import(/* webpackChunkName: 'videoListPorn1' */'../../tpl/porn1/components/videoList'),
        discoverPorn1: () => import(/* webpackChunkName: 'discoverPorn1' */'../../tpl/porn1/components/discover'),
        artistPorn1: () => import(/* webpackChunkName: 'artistPorn1' */'../../tpl/porn1/components/artist'),
        searchPorn1: () => import(/* webpackChunkName: 'searchPorn1' */'../../tpl/porn1/components/search'),
        tagPorn1: () => import(/* webpackChunkName: 'tagPorn1' */'../../tpl/porn1/components/tag'),
        joinMemberPorn1: () => import(/* webpackChunkName: 'joinMemberPorn1' */'../../tpl/porn1/components/joinMember'),
        liveStreamPorn1: () => import(/* webpackChunkName: 'liveStreamPorn1' */'../../tpl/porn1/components/liveStream'),
        fishareaPorn1: () => import(/* webpackChunkName: 'fishareaPorn1' */'../../tpl/porn1/components/fisharea'),
        servicePorn1: () => import(/* webpackChunkName: 'servicePorn1' */'../../tpl/porn1/components/service'),
        webviewPorn1: () => import(/* webpackChunkName: 'webviewPorn1' */'../../tpl/porn1/components/webview'),
        installPorn1: () => import(/* webpackChunkName: 'installPorn1' */'../../tpl/porn1/components/install'),
        shareDownloadPorn1: () => import(/* webpackChunkName: 'shareDownloadPorn1' */ '../../tpl/porn1/components/shareDownload'),
        launchPorn1: () => import(/* webpackChunkName: 'launchPorn1' */ '../../tpl/porn1/components/launch'),
        withdrawAccountPorn1: () => import(/* webpackChunkName: 'withdrawAccountPorn1' */ '../../common/withdrawAccount/withdrawAccount'),
        agLoginPorn1: () => import(/* webpackChunkName: 'agLoginPorn1' */'../../tpl/porn1/components/agLogin/components'),
        joinAgentPorn1: () => import(/* webpackChunkName: 'joinAgentPorn1' */'../../tpl/porn1/components/joinAgent/components')
    },
    mcenter: {
        homePorn1: () => import(/* webpackChunkName: 'homePorn1' */'../../tpl/porn1/components/mcenter/components/home'),
        accountDataPorn1: () => import(/* webpackChunkName: 'accountDataPorn1' */'../../tpl/porn1/components/mcenter/components/accountData'),
        // bindingDevicePorn1: () => import(/* webpackChunkName: 'bindingDevicePorn1' */'../../tpl/porn1/components/mcenter/components/bindingDevice'),
        balanceTransPorn1: () => import(/* webpackChunkName: 'balanceTransPorn1' */'../../tpl/porn1/components/mcenter/components/balanceTrans'),
        creditTransPorn1: () => import(/* webpackChunkName: 'creditTransPorn1' */'../../tpl/porn1/components/mcenter/components/creditTrans'),
        bankCardPorn1: () => import(/* webpackChunkName: 'bankCardPorn1' */'../../tpl/porn1/components/mcenter/components/bankCard'),
        bankRebatePorn1: () => import(/* webpackChunkName: 'bankRebatePorn1' */'../../tpl/porn1/components/mcenter/components/bankRebate'),
        betRecordPorn1: () => import(/* webpackChunkName: 'betRecordPorn1' */'../../tpl/porn1/components/mcenter/components/betRecord'),
        // bonusAccountPorn1: () => import(/* webpackChunkName: 'bonusAccountPorn1' */'../../tpl/porn1/components/mcenter/components/bonusAccount'),
        moneyDetailPorn1: () => import(/* webpackChunkName: 'moneyDetailPorn1' */'../../tpl/porn1/components/mcenter/components/moneyDetail'),
        informationPorn1: () => import(/* webpackChunkName: 'informationPorn1' */'../../tpl/porn1/components/mcenter/components/information'),
        withdrawPorn1: () => import(/* webpackChunkName: 'withdrawPorn1' */'../../tpl/porn1/components/mcenter/components/withdraw'),
        depositPorn1: () => import(/* webpackChunkName: 'depositPorn1' */'../../tpl/porn1/components/mcenter/components/deposit'),
        accountVipPorn1: () => import(/* webpackChunkName: 'accountVipPorn1' */'../../tpl/porn1/components/mcenter/components/accountVip'),
        accountVipDetailPorn1: () => import(/* webpackChunkName: 'accountVipDetailPorn1' */'../../tpl/porn1/components/mcenter/components/vipDetail'),
        tcenterCommissionPorn1: () => import(/* webpackChunkName: 'tcenterCommissionPorn1' */'../../tpl/porn1/components/mcenter/components/tcenter/components/commission'),
        tcenterGameRecordPorn1: () => import(/* webpackChunkName: 'tcenterGameRecordPorn1' */'../../tpl/porn1/components/mcenter/components/tcenter/components/gameRecord'),
        tcenterManagementPorn1: () => import(/* webpackChunkName: 'tcenterManagementPorn1' */'../../tpl/porn1/components/mcenter/components/tcenter/components/management'),
        tcenterRecommendGiftPorn1: () => import(/* webpackChunkName: 'tcenteRecommendGiftPorn1' */'../../tpl/porn1/components/mcenter/components/tcenter/components/recommendGift'),
        aboutPorn1: () => import(/* webpackChunkName: 'aboutPorn1' */'../../tpl/porn1/components/mcenter/components/about'),
        settingPorn1: () => import(/* webpackChunkName: 'settingPorn1' */'../../tpl/porn1/components/mcenter/components/setting'),
        feedbackPorn1: () => import(/* webpackChunkName: 'feedbackPorn1' */'../../tpl/porn1/components/mcenter/components/feedback'),
        helpPorn1: () => import(/* webpackChunkName: 'helpPorn1' */'../../tpl/porn1/components/mcenter/components/help/components'),
        helpCenterPorn1: () => import(/* webpackChunkName: 'helpCenterPorn1' */'../../tpl/porn1/components/mcenter/components/help'),
        helpDetailPorn1: () => import(/* webpackChunkName: 'helpDetailPorn1' */'../../tpl/porn1/components/mcenter/components/help/components/detail'),
        accountDataAliasPorn1: () => import(/* webpackChunkName: 'accountDataAliasPorn1' */'../../tpl/porn1/components/mcenter/components/accountData/components/account/form/editAlias'),
        accountDataNamePorn1: () => import(/* webpackChunkName: 'accountDataNamePorn1' */'../../tpl/porn1/components/mcenter/components/accountData/components/account/form/editName'),
        accountDataPhonePorn1: () => import(/* webpackChunkName: 'accountDataPhonePorn1' */'../../tpl/porn1/components/mcenter/components/accountData/components/account/form/editPhone'),
        accountDataEmailPorn1: () => import(/* webpackChunkName: 'accountDataEmailPorn1' */'../../tpl/porn1/components/mcenter/components/accountData/components/account/form/editEmail'),
        accountDataQqPorn1: () => import(/* webpackChunkName: 'accountDataQqPorn1' */'../../tpl/porn1/components/mcenter/components/accountData/components/account/form/editQq'),
        accountDataLinePorn1: () => import(/* webpackChunkName: 'accountDataLinePorn1' */'../../tpl/porn1/components/mcenter/components/accountData/components/account/form/editLine'),
        accountDataWeixinPorn1: () => import(/* webpackChunkName: 'accountDataWeixinPorn1' */'../../tpl/porn1/components/mcenter/components/accountData/components/account/form/editWeixin'),
        accountDataBirthdayPorn1: () => import(/* webpackChunkName: 'accountDataBirthdayPorn1' */'../../tpl/porn1/components/mcenter/components/accountData/components/account/form/editBirthday'),
        accountDataWithdrawpwdPorn1: () => import(/* webpackChunkName: 'accountDataWithdrawpwdPorn1' */'../../tpl/porn1/components/mcenter/components/accountData/components/account/form/editWithdrawPwd'),
        walletPorn1: () => import(/* webpackChunkName: 'walletPorn1' */'../../tpl/porn1/components/mcenter/components/wallet'),
        makeMoneyPorn1: () => import(/* webpackChunkName: 'makeMoneyPorn1' */'../../tpl/porn1/components/mcenter/components/makeMoney')
    },
    agcenter: {
        homePorn1: () => import(/* webpackChunkName: 'homePorn1' */'../../tpl/porn1/components/agcenter/components/home/components'),
        accountDataPorn1: () => import(/* webpackChunkName: 'accountDataPorn1' */'../../tpl/porn1/components/agcenter/components/accountData/components'),
        bankCardPorn1: () => import(/* webpackChunkName: 'bankCardPorn1' */'../../tpl/porn1/components/agcenter/components/bankCard/components'),
        financeRewardPorn1: () => import(/* webpackChunkName: 'financeRewardPorn1' */'../../tpl/porn1/components/agcenter/components/financeReward/components'),
        financeWithdrawPorn1: () => import(/* webpackChunkName: 'financeWithdrawPorn1' */'../../tpl/porn1/components/agcenter/components/financeWithdraw/components'),
        gameRecordPorn1: () => import(/* webpackChunkName: 'gameRecordPorn1' */'../../tpl/porn1/components/agcenter/components/gameRecord/components'),
        messagePorn1: () => import(/* webpackChunkName: 'messagePorn1' */'../../tpl/porn1/components/agcenter/components/message/components'),
        postPorn1: () => import(/* webpackChunkName: 'postPorn1' */'../../tpl/porn1/components/agcenter/components/post/components'),
        feedBackPorn1: () => import(/* webpackChunkName: 'feedBackPorn1' */'../../tpl/porn1/components/agcenter/components/feedBack/components'),
        reportMemberPorn1: () => import(/* webpackChunkName: 'reportMemberPorn1' */'../../tpl/porn1/components/agcenter/components/reportMember/components')
    }
};
